package com.aesp.backend.dto.match;

import lombok.Data;

@Data
public class MatchRequest {
    private String clientId; // generated by client to identify itself
    private String topic; // e.g., "Travel"
    private String level; // e.g., "Beginner", "Intermediate"
}
